language: node_js
node_js:
  - '8'
  - '9'
  - '10'
install:
  - npm install -g codecov
script:
  - yarn install
  - yarn test:coverage --runInBand --no-cache
  - codecov
cache:
  directories:
    - node_modules
